trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
 - script: | 
             wget https://github.com/sstephenson/bats/archive/v0.4.0.zip -O /tmp/bats.zip
             export ALLOW_RUNASROOT=1; mkdir /usr/local/bin/bats && unzip /tmp/bats.zip -d /usr/local/bin/bats  
   displayName: 'Install bats'
 
 - script: command -v bats 
   displayName: 'check bats'

 - script: bash -c 'shopt -s globstar; shellcheck ./bin/tfvm'
   displayName: 'Run shellcheck'

