variables:
    bats: '/tmp/bats/bin/bats' 

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
 - script: | 
             wget https://github.com/sstephenson/bats/archive/v0.4.0.zip -O /tmp/bats.zip
             unzip /tmp/bats.zip -d /tmp
             mv /tmp/bats-0.4.0 /tmp/bats
   displayName: 'Install bats'
   
 - script: $(bats) -v  
   displayName: 'check bats'

 - script: bash -c 'shopt -s globstar; shellcheck ./bin/tfvm'
   displayName: 'Run shellcheck'
