variables:
    BATS_ROOT: '/tmp/bats' 
    TFVMDIR: '$(Build.SourcesDirectory)'
trigger:
- master

pr:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
   - script: |
              echo '##vso[task.prependpath]$(TFVMDIR)/bin'
              echo '##vso[task.prependpath]$(TFVMDIR)/bin/shims'
              echo '##vso[task.prependpath]$(BATS_ROOT)/bin/bats'
     displayName: 'add tfvm and bats path'
   - script: | 
             wget https://github.com/sstephenson/bats/archive/v0.4.0.zip -O /tmp/bats.zip
             unzip /tmp/bats.zip -d /tmp
             mv /tmp/bats-0.4.0 /tmp/bats
             
     displayName: 'Install bats'
   
   - script: bats -v  
     displayName: 'check bats'

   - script: bash -c 'shopt -s globstar; shellcheck ./bin/tfvm'
     displayName: 'Run shellcheck'

   - script: 'bats ./tests/test.bats'  
     displayName: 'Run tests'
