trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
 - script: |
            curl https://github.com/sstephenson/bats/archive/v0.4.0.zip -o /tmp/bats.zip 
            mkdir /usr/local/bin/bats 
            unzip /tmp/bats.zip -d /usr/local/bin/bats  
   displayName: 'Install bats'
   workingDirectory: '/tmp' 
 
 - script: command -v bats 
   displayName: 'check bats'

 - script: bash -c 'shopt -s globstar; shellcheck ./bin/tfvm'
   displayName: 'Run shellcheck'

