trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
 - script: | 
             wget https://github.com/sstephenson/bats/archive/v0.4.0.zip -O /tmp/bats.zip
             unzip /tmp/bats.zip 
             mv bats-0.4.0 bats
             export BATS_ROOT=/tmp/bats/bin:$PATH  
   displayName: 'Install bats'
 
 - script: command -v bats 
   displayName: 'check bats'

 - script: bash -c 'shopt -s globstar; shellcheck ./bin/tfvm'
   displayName: 'Run shellcheck'

