variables:
    bats: '/tmp/bats/bin/bats' 
    TFVMDIR: '$(Build.SourcesDirectory)'
trigger:
- master

pr:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
   - script: |
              echo '##vso[task.prependpath]$(TFVMDIR)/bin'
              echo '##vso[task.prependpath]$(TFVMDIR)/bin/shims'
              
     displayName: 'add tfvm'
   - script: | 
             wget https://github.com/bats-core/bats-core/archive/v1.1.0.zip -O /tmp/bats.zip
             unzip /tmp/bats.zip -d /tmp
             mv /tmp/bats-core-1.1.0 /tmp/bats
     displayName: 'Install bats'
   
   - script: $(bats) -v  
     displayName: 'check bats'

   - script: bash -c 'shopt -s globstar; shellcheck ./bin/tfvm; shellcheck bash_completion'
     displayName: 'Run shellcheck'

   - script: '$(bats) ./tests/test.bats'  
     displayName: 'Run tests'

- job: macOS
  pool:
    vmImage: 'macOS 10.13'
  steps:
   - script: |
              echo '##vso[task.prependpath]$(TFVMDIR)/bin'
              echo '##vso[task.prependpath]$(TFVMDIR)/bin/shims'
              
     displayName: 'add tfvm path'
   - script: | 
              brew install shellcheck
              brew install bats
     displayName: 'Install dependencies'
      
   - script: bash -c 'shopt -s globstar; shellcheck ./bin/tfvm; shellcheck bash_completion'
     displayName: 'Run shellcheck'

   - script: 'bats ./tests/test.bats'  
     displayName: 'Run tests'

